name: Ruby specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Specs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '3.0']
        experimental: [false]

        include:
          - ruby-version: 'head'
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake
